name: Build and push docker image into gh package registry
# DO not push again on new tags
on:
  push:
    branches-ignore:
      - refs/tags/*
env:
  DOCKER_IMAGE_ORG: ghcr.io/johnsmithdoe970
  DOCKER_IMAGE_REPO: ps4jb-master
  DOCKER_IMAGE_TAG: latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env vars
        run: |
          echo "build_date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "last_upstream_commit=$(git log -1 --grep 'Squashed.*' | awk '/git-subtree-split/{ print $2;}')" >> $GITHUB_ENV
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Update upstream
        run: ./update-upstream.sh
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "${{ env.DOCKER_IMAGE_ORG }}/${{ env.DOCKER_IMAGE_REPO }}:${{ env.DOCKER_IMAGE_TAG }}"
          labels: |
            org.opencontainers.image.source=https://github.com/johnsmithdoe970/ps4-container/
            org.opencontainers.image.created=${{ env.build_date }}
            org.opencontainers.image.description=Container with static content of PS4JB
            org.opencontainers.image.version=${{ env.last_upstream_commit }}
